### ISSUE TITLE
Newbie, error on running pibackup

### ISSUE THREAD

**Issue by ekantrowitz** [Chocorean/pibackup#10]
Just tried to run pibackup for the first time.  I got the following error:
fatal: not a git repository (or any of the parent directories): git
Not sure why I am getting a git error.

Then
[pibackup.sh] Dumping sdcard ...

with system hang, checked the process and it reads 00:00:00 after some period of time

**Comment by Chocorean** [comment]
Hello, thanks for reaching out, could you please show me how you download and use the script? Thanks
